### PR TITLE
Mystery and YAML functionality

### PR DESCRIPTION
**Pull request by Catobat**
YAML files can be used to save both normal presets and fully customizable weightsets for Mystery games, meaning players have to figure out the settings as they play, or to just generate random settings that they're allowed to look at before playing.
In detail, this includes the following changes:

- Presets in the UI are no longer saved as settings strings, but rather as YAML files placed in a specific folder relative to the randomizer. This will make presets from older versions compatible with newer versions.
- Mystery weight presets are also available in the UI.
- When generating a seed, the user can choose to load options from a YAML file (only logic setting, only cosmetic settings, both from two separate files or both together from one file). These will override the settings previously selected in the UI or CLI. This allows for generating Mystery seeds without being spoiled the settings. The settings hash won't be written to the game and the settings string won't be displayed in the UI on the "Seed Output" tab (but can still be retrieved through a button click or the spoiler log).
- YAML files can also be directly loaded into the UI or CLI prior to generation, for random settings that are supposed to be known before the start, or for producing samples for what a given Mystery YAML file can potentially produce, or for presets without randomness.
- A method for players to be able to check certain goal-related settings in the game has been implemented. Players can now talk to Gentari (the elder in the Minish Village) after obtaining the Jabber Nut to be given information about the settings in the "Requirements" category. This is important information in Mystery seeds.
- It is not possible to edit Mystery YAML files through the UI, only preset files. However, a template Mystery file containing all settings can be generated through a menu button which can be edited in a text editor. Of course, the existing weight presets can also be used as a basis. Custom Mystery files can then be placed in the respective preset folder to appear in the UI on future loads, or can be loaded by choosing the file under "Use Global YAML File" if enabled.
- YAML files support subweights to make it possible to link certain setting combinations or chances together.
- The file YAML_Documentation.md details how YAML files need to be formatted. In practice it should usually suffice to look at existing files to understand the format.

Currently no proper presets are included, these will be added soon and include the new options recently added in other branches.

### CODE REVIEW

**Comment by Myth197** [comment]
Ignore those last 2 commits, we were confused when resolving merge conflicts

**Comment by Dreamie-TMC** [comment]
Blocking this for now - I'm going to do a big change in the RandomizerCore code because the code is no longer readable

**Review by Dreamie-TMC — CHANGES_REQUESTED** [review]
Blocking for now - see other comment

I'm likely going to have to revert what I did, we lost a ton of functionality in the merge, but we will see, the base branch was so far behind that it might not be salvageable and may require cherry picking commits

**Review by Myth197 — COMMENTED** [review]
Logic and Patches have been resolved

**Review by Dreamie-TMC — APPROVED** [review]

**Comment by Dreamie-TMC** [comment]
Closes #66

**Pull request merged**
